/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'hello.Debug+NUCLEO-G474RE' 
 * Target:  'Debug+NUCLEO-G474RE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device&STM32CubeMX:STM32Cube HAL@1.4.0 */
#define USE_HAL_DRIVER
#define USE_FULL_LL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
