/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0-dev3
 *
 * Project: 'hello.Debug+NUCLEO-G474RE' 
 * Target:  'Debug+NUCLEO-G474RE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32g4xx.h"

/* ARM::CMSIS-Compiler:I/O:STDOUT:User:1.0.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
        #define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */
/* ARM::CMSIS:RTOS2:Keil RTX5:Source:5.5.4 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil.STM32CubeMX::Device:STM32Cube Framework:STM32CubeMX:1.4.0 */
#define RTE_DEVICE_FRAMEWORK_CUBE_MX
/* Keil.STM32CubeMX::Device:STM32Cube HAL:1.4.0 */
#define RTE_DEVICE_CUBE_MX_HAL


#endif /* RTE_COMPONENTS_H */
